name = "abdulshukor"    
compatibility_date = "2025-11-15"    
    
[[routes]]    
pattern = "abdulshukor"    
custom_domain = true    
    
[[routes]]    
pattern = "www.abdulshukor"    
custom_domain = true    
    
[build]    
command = "hugo"    
    
[assets]    
directory = "./public"    
not_found_handling = "404-page"